
name: CI

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:
run-name: Space Word test

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout   
        uses: actions/checkout@v4 
      - name: Setup Node   
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies  
        run: npm ci
      - name: Npm Linter
        run: npm run lint
        continue-on-error: true
      - name: Unit Testing
        run: npm test
      - name: Install Playwright
        run: npx playwright install
      - name: Functional Tests
        run: npm run playwright
      - name: Npm Audit
        run: npm audit 
      - name: Docker Compose
        run: docker compose build
        continue-on-error: true
      - name: Résumé
        run: |
          echo "::notice::Pipeline CI terminée avec succès"
          echo "## Résumé de la pipeline" >> $GITHUB_STEP_SUMMARY